dist: jammy
addons:
  chrome: stable
language: node_js
services:
- xvfb
node_js:
- lts/*
cache: false
before_install:
- export DEMOS_PATH=$( $TRAVIS_BUILD_DIR )
- npm i -g http-server
- npm i -g yarn
install:
- cd ./tests && yarn install
script:
- ./tests/scripts/travis.sh