version: 2.1

jobs:
  test-demos:
    docker:
      - image: cimg/node:18.17.1
        user: root
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd tests && yarn
            npm i -g http-server
      - run:
          name: Test each demo
          command: bash tests/scripts/build-and-test-demos.sh

workflows:
  commit-workflow:
    jobs:
      - test-demos
